/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

/**
 *
 * @author matheus
 */
public class Calculadora extends javax.swing.JFrame {
        double valor1, valor2, resultado;
        String operacao;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        bntBotaoPorc = new javax.swing.JButton();
        bntBotaoRaiz = new javax.swing.JButton();
        bntBotaoElev = new javax.swing.JButton();
        bntBotaoCE = new javax.swing.JButton();
        bntBotaoC = new javax.swing.JButton();
        bntBotaoDel = new javax.swing.JButton();
        bntBotao7 = new javax.swing.JButton();
        bntBotao8 = new javax.swing.JButton();
        bntBotao9 = new javax.swing.JButton();
        bntBotao4 = new javax.swing.JButton();
        bntBotao5 = new javax.swing.JButton();
        bntBotao6 = new javax.swing.JButton();
        bntBotao3 = new javax.swing.JButton();
        bntBotao2 = new javax.swing.JButton();
        bntBotao1 = new javax.swing.JButton();
        bntMaisorMenos = new javax.swing.JButton();
        bntBotao0 = new javax.swing.JButton();
        bntPonto = new javax.swing.JButton();
        bntBotaoDiv = new javax.swing.JButton();
        bntMulti = new javax.swing.JButton();
        bntSub = new javax.swing.JButton();
        bntSoma = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        bntIgual = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntBotaoPorc.setText("%");
        bntBotaoPorc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotaoPorcActionPerformed(evt);
            }
        });

        bntBotaoRaiz.setText("√");
        bntBotaoRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotaoRaizActionPerformed(evt);
            }
        });

        bntBotaoElev.setText("x²");
        bntBotaoElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotaoElevActionPerformed(evt);
            }
        });

        bntBotaoCE.setText("CE");
        bntBotaoCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotaoCEActionPerformed(evt);
            }
        });

        bntBotaoC.setText("C");
        bntBotaoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotaoCActionPerformed(evt);
            }
        });

        bntBotaoDel.setText("DEL");
        bntBotaoDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotaoDelActionPerformed(evt);
            }
        });

        bntBotao7.setText("7");
        bntBotao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotao7ActionPerformed(evt);
            }
        });

        bntBotao8.setText("8");
        bntBotao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotao8ActionPerformed(evt);
            }
        });

        bntBotao9.setText("9");
        bntBotao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotao9ActionPerformed(evt);
            }
        });

        bntBotao4.setText("4");
        bntBotao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotao4ActionPerformed(evt);
            }
        });

        bntBotao5.setText("5");
        bntBotao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotao5ActionPerformed(evt);
            }
        });

        bntBotao6.setText("6");
        bntBotao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotao6ActionPerformed(evt);
            }
        });

        bntBotao3.setText("3");
        bntBotao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotao3ActionPerformed(evt);
            }
        });

        bntBotao2.setText("2");
        bntBotao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotao2ActionPerformed(evt);
            }
        });

        bntBotao1.setText("1");
        bntBotao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotao1ActionPerformed(evt);
            }
        });

        bntMaisorMenos.setText("+/-");
        bntMaisorMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMaisorMenosActionPerformed(evt);
            }
        });

        bntBotao0.setText("0");
        bntBotao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotao0ActionPerformed(evt);
            }
        });

        bntPonto.setText(".");
        bntPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPontoActionPerformed(evt);
            }
        });

        bntBotaoDiv.setText("÷");
        bntBotaoDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBotaoDivActionPerformed(evt);
            }
        });

        bntMulti.setText("×");
        bntMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMultiActionPerformed(evt);
            }
        });

        bntSub.setText("-");
        bntSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSubActionPerformed(evt);
            }
        });

        bntSoma.setText("+");
        bntSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSomaActionPerformed(evt);
            }
        });

        jLabel1.setText("Calculadora");

        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bntIgual.setText("=");
        bntIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bntBotaoCE, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(bntBotaoPorc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bntBotao7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bntBotaoC, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(bntBotaoRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bntBotao8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bntBotao1)
                                    .addComponent(bntBotao4)
                                    .addComponent(bntMaisorMenos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bntBotao5)
                                    .addComponent(bntBotao2)
                                    .addComponent(bntBotao0, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntBotao9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntBotao6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntBotao3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntPonto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntBotaoDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(bntBotaoElev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(bntBotaoDiv)
                            .addComponent(bntMulti)
                            .addComponent(bntSub)
                            .addComponent(bntIgual)
                            .addComponent(bntSoma))
                        .addContainerGap(183, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtResultado)
                        .addGap(183, 183, 183))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bntBotao0, bntBotao1, bntBotao2, bntBotao3, bntBotao4, bntBotao5, bntBotao6, bntBotao7, bntBotao8, bntBotao9, bntBotaoC, bntBotaoCE, bntBotaoDel, bntBotaoDiv, bntBotaoElev, bntBotaoRaiz, bntIgual, bntMaisorMenos, bntMulti, bntPonto, bntSoma, bntSub});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntBotaoPorc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntBotaoRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntBotaoElev, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntBotaoCE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntBotaoC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntBotaoDel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bntBotao7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bntBotao4)
                                    .addComponent(bntBotao5)
                                    .addComponent(bntBotao6)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bntBotao9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bntBotao8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntBotao1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bntBotao2)
                                .addComponent(bntBotao3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntMaisorMenos)
                            .addComponent(bntBotao0)
                            .addComponent(bntPonto)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bntBotaoDiv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(bntSub))
                            .addComponent(bntMulti))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntSoma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntIgual)))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bntBotao0, bntBotao1, bntBotao2, bntBotao3, bntBotao4, bntBotao5, bntBotao6, bntBotao7, bntBotao8, bntBotao9, bntBotaoC, bntBotaoCE, bntBotaoDel, bntBotaoDiv, bntBotaoElev, bntBotaoPorc, bntBotaoRaiz, bntIgual, bntMaisorMenos, bntMulti, bntPonto, bntSoma, bntSub});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntBotaoRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotaoRaizActionPerformed
    valor1 = Double.parseDouble(txtResultado.getText());
    resultado = Math.sqrt(valor1);
    txtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_bntBotaoRaizActionPerformed

    private void bntBotao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotao7ActionPerformed
    txtResultado.setText(txtResultado.getText() + "7");
    }//GEN-LAST:event_bntBotao7ActionPerformed

    private void bntBotao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotao4ActionPerformed
    txtResultado.setText(txtResultado.getText() + "4");
    }//GEN-LAST:event_bntBotao4ActionPerformed

    private void bntBotaoDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotaoDivActionPerformed
    valor1 = Double.parseDouble(txtResultado.getText());
    operacao = "divisao"; 
    txtResultado.setText("");
    }//GEN-LAST:event_bntBotaoDivActionPerformed

    private void bntBotao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotao0ActionPerformed
       txtResultado.setText(txtResultado.getText()+"0");
    }//GEN-LAST:event_bntBotao0ActionPerformed

    private void bntBotao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotao2ActionPerformed
        txtResultado.setText(txtResultado.getText()+"2");
    }//GEN-LAST:event_bntBotao2ActionPerformed

    private void bntBotao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotao1ActionPerformed
        txtResultado.setText(txtResultado.getText()+"1");
    }//GEN-LAST:event_bntBotao1ActionPerformed

    private void bntSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSomaActionPerformed
    valor1 = Double.parseDouble(txtResultado.getText());
    operacao = "soma"; 
    txtResultado.setText("");
    }//GEN-LAST:event_bntSomaActionPerformed

    private void bntIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIgualActionPerformed
    valor2 = Double.parseDouble(txtResultado.getText());

    switch (operacao) {
        case "soma": resultado = valor1 + valor2; break;
        case "subtracao": resultado = valor1 - valor2; break;
        case "multiplicacao": resultado = valor1 * valor2; break;
        case "divisao": 
            if(valor2 == 0){ txtResultado.setText("Erro"); return; }
            resultado = valor1 / valor2; 
            break;
    }
    txtResultado.setText(String.valueOf(resultado));  
    }//GEN-LAST:event_bntIgualActionPerformed

    private void bntBotao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotao5ActionPerformed
    txtResultado.setText(txtResultado.getText() + "5");
    }//GEN-LAST:event_bntBotao5ActionPerformed

    private void bntBotao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotao3ActionPerformed
    txtResultado.setText(txtResultado.getText() + "3");    }//GEN-LAST:event_bntBotao3ActionPerformed

    private void bntBotao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotao6ActionPerformed
    txtResultado.setText(txtResultado.getText() + "6");    }//GEN-LAST:event_bntBotao6ActionPerformed

    private void bntBotao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotao8ActionPerformed
    txtResultado.setText(txtResultado.getText() + "8");    }//GEN-LAST:event_bntBotao8ActionPerformed

    private void bntBotao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotao9ActionPerformed
    txtResultado.setText(txtResultado.getText() + "9");    }//GEN-LAST:event_bntBotao9ActionPerformed

    private void bntBotaoCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotaoCEActionPerformed
    txtResultado.setText(""); 
    }//GEN-LAST:event_bntBotaoCEActionPerformed

    private void bntBotaoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotaoCActionPerformed
    txtResultado.setText("");
    valor1 = valor2 = resultado = 0;
    operacao = "";
    }//GEN-LAST:event_bntBotaoCActionPerformed

    private void bntBotaoDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotaoDelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntBotaoDelActionPerformed

    private void bntBotaoPorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotaoPorcActionPerformed
    valor1 = Double.parseDouble(txtResultado.getText());
    resultado = valor1 / 100;
    txtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_bntBotaoPorcActionPerformed

    private void bntBotaoElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBotaoElevActionPerformed
    valor1 = Double.parseDouble(txtResultado.getText());
    resultado = valor1 * valor1;
    txtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_bntBotaoElevActionPerformed

    private void bntMaisorMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMaisorMenosActionPerformed
    double temp = Double.parseDouble(txtResultado.getText());
    temp = temp * -1;
    txtResultado.setText(String.valueOf(temp));
    }//GEN-LAST:event_bntMaisorMenosActionPerformed

    private void bntPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntPontoActionPerformed

    private void bntSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSubActionPerformed
    valor1 = Double.parseDouble(txtResultado.getText());
    operacao = "subtracao"; 
    txtResultado.setText("");
    }//GEN-LAST:event_bntSubActionPerformed

    private void bntMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMultiActionPerformed
    valor1 = Double.parseDouble(txtResultado.getText());
    operacao = "multiplicacao"; 
    txtResultado.setText("");
    }//GEN-LAST:event_bntMultiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBotao0;
    private javax.swing.JButton bntBotao1;
    private javax.swing.JButton bntBotao2;
    private javax.swing.JButton bntBotao3;
    private javax.swing.JButton bntBotao4;
    private javax.swing.JButton bntBotao5;
    private javax.swing.JButton bntBotao6;
    private javax.swing.JButton bntBotao7;
    private javax.swing.JButton bntBotao8;
    private javax.swing.JButton bntBotao9;
    private javax.swing.JButton bntBotaoC;
    private javax.swing.JButton bntBotaoCE;
    private javax.swing.JButton bntBotaoDel;
    private javax.swing.JButton bntBotaoDiv;
    private javax.swing.JButton bntBotaoElev;
    private javax.swing.JButton bntBotaoPorc;
    private javax.swing.JButton bntBotaoRaiz;
    private javax.swing.JButton bntIgual;
    private javax.swing.JButton bntMaisorMenos;
    private javax.swing.JButton bntMulti;
    private javax.swing.JButton bntPonto;
    private javax.swing.JButton bntSoma;
    private javax.swing.JButton bntSub;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
