/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PrimeirasInterfaces;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matheus
 */
public class RadioButtonTeste extends javax.swing.JFrame {
    String sexo;
    boolean tecnologia, astronomia, esportes;
    /**
     * Creates new form RadioButton
     */
    public RadioButtonTeste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp_Sexo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        RButtonMasc = new javax.swing.JRadioButton();
        RButtonFem = new javax.swing.JRadioButton();
        LabelNome = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        bntSalvar = new javax.swing.JButton();
        chk_Tecnologia = new javax.swing.JCheckBox();
        chk_Astronomia = new javax.swing.JCheckBox();
        chk_Esportes = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_Idioma = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Pessoas = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btnGrp_Sexo.add(RButtonMasc);
        RButtonMasc.setText("Masculino");
        RButtonMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButtonMascActionPerformed(evt);
            }
        });

        btnGrp_Sexo.add(RButtonFem);
        RButtonFem.setText("Feminino");
        RButtonFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButtonFemActionPerformed(evt);
            }
        });

        LabelNome.setText("Nome:");

        lblSexo.setText("Sexo");

        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        chk_Tecnologia.setText("Tecnologia");
        chk_Tecnologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_TecnologiaActionPerformed(evt);
            }
        });

        chk_Astronomia.setText("Astronomia");
        chk_Astronomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_AstronomiaActionPerformed(evt);
            }
        });

        chk_Esportes.setText("Esportes");
        chk_Esportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_EsportesActionPerformed(evt);
            }
        });

        jLabel1.setText("Interesse:");

        jLabel2.setText("Idioma");

        cmb_Idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Português", "Inglês", "Espanhol", "Alemão" }));

        tbl_Pessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "Idioma"
            }
        ));
        jScrollPane2.setViewportView(tbl_Pessoas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSexo)
                    .addComponent(LabelNome))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RButtonMasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RButtonFem))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chk_Tecnologia)
                        .addGap(18, 18, 18)
                        .addComponent(chk_Astronomia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_Esportes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(bntSalvar))
                    .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(RButtonMasc)
                    .addComponent(RButtonFem))
                .addGap(18, 18, 18)
                .addComponent(bntSalvar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_Tecnologia)
                    .addComponent(chk_Astronomia)
                    .addComponent(chk_Esportes)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void RButtonFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RButtonFemActionPerformed

    private void RButtonMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RButtonMascActionPerformed

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
    if(RButtonMasc.isSelected()){
        sexo = "M";
        JOptionPane.showMessageDialog(null, 
                "Sexo selecionado: "+sexo,"Alerta",JOptionPane.WARNING_MESSAGE);
    }
    else if(RButtonFem.isSelected()){
        sexo = "F";
        JOptionPane.showMessageDialog(null, 
            "Sexo selecionado: "+sexo,"Alerta",JOptionPane.WARNING_MESSAGE);
    }
    else{
                JOptionPane.showMessageDialog(null, 
            "Sexo selecionado: "+sexo,"Erro!",JOptionPane.WARNING_MESSAGE);
    }
    
    if(chk_Tecnologia.isSelected()){
        tecnologia = true;
    }
    else{
        tecnologia = false;
    }
    if(chk_Astronomia.isSelected()){
        astronomia = true;
    }
    else{
        astronomia = false;
    }
            if(chk_Esportes.isSelected()){
        esportes = true;
    }
    else{
        esportes = false;
    }
            //JOptionPane.showMessageDialog(null,"tecnologia: "+tecnologia+"\nAstronomia: "+astronomia+"\nEsportes: "+esportes, "Alerta",JOptionPane.INFORMATION_MESSAGE);
            //JOptionPane.showConfirmDialog(null, 
                    //"Idioma selecionado: "+cmb_Idioma.getSelectedItem(),
                    //"Alerta", JOptionPane.INFORMATION_MESSAGE);
                    Pessoa p = new Pessoa(txtNome.getText(),sexo, (String) cmb_Idioma.getSelectedItem());
                    DefaultTableModel tabela = (DefaultTableModel) tbl_Pessoas.getModel();
                    tabela.addRow(p.obterDados());
                    
    txtNome.setText("");
    btnGrp_Sexo.clearSelection();
    chk_Tecnologia.setSelected(false);
    chk_Astronomia.setSelected(false);
    chk_Esportes.setSelected(false);
    cmb_Idioma.setSelectedIndex(0);

                    
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void chk_EsportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_EsportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_EsportesActionPerformed

    private void chk_AstronomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_AstronomiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_AstronomiaActionPerformed

    private void chk_TecnologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_TecnologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_TecnologiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButtonTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButtonTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButtonTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButtonTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButtonTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNome;
    private javax.swing.JRadioButton RButtonFem;
    private javax.swing.JRadioButton RButtonMasc;
    private javax.swing.JButton bntSalvar;
    private javax.swing.ButtonGroup btnGrp_Sexo;
    private javax.swing.JCheckBox chk_Astronomia;
    private javax.swing.JCheckBox chk_Esportes;
    private javax.swing.JCheckBox chk_Tecnologia;
    private javax.swing.JComboBox<String> cmb_Idioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JTable tbl_Pessoas;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
